### ISSUE TITLE
Palavra "reiniciar" escrita de forma incorreta

### ISSUE THREAD

**Issue by diegozl** [discloud/vscode-discloud#15]
Oi, pessoal.

Apenas uma observação rápida, mas que, obviamente, não muda em nada a experiência com a Discloud. É apenas para tornar a Discloud cada vez mais profissional, angariando cada vez mais clientes.

![discloud](https://user-images.githubusercontent.com/52968011/208342391-a7c29211-255e-43f2-b1ee-3a2eda381a92.png)

**Comment by Gorniaky** [comment]
Corrigido na 2.0, obrigado!
